Yes, you can handle multiple exceptions in a single except block in Python.
EX.

```python
try:
    result=10/0
except (ZeroDivisionError, ValueError) as e:
    print(f"An error occurred: {e}")
```